apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-api-deployment
  namespace: app
  labels: 
    documents-api: first
spec:
  replicas: 1
  selector:
    matchLabels:
      documents-api: first
  template:
    metadata:
      labels:
        documents-api: first
    spec:
      imagePullSecrets:
      - name: harbor-credentials
      containers:
      - name: documents-api
        image: harbor.1.2.3.4.nip.io/app/documentsapi:v1
        envFrom:
        - configMapRef:
            name: documents-api-configmap
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 3001
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "curl -f http://127.0.0.1:3001/documents/health-check | grep -q 'configuration'"
          initialDelaySeconds: 15
          periodSeconds: 15
