apiVersion: v1
kind: ConfigMap
metadata:
  name: documents-api-configmap
  namespace: app
data:
  DATABASE_NAME: "otus_documents_db"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  PORT: "3001"
  HOST: "0.0.0.0"