apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-configmap
  namespace: app
data:
  DATABASE_NAME: "otus_users_db"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  PORT: "3000"
  HOST: "0.0.0.0"